
###------------------------------
###Create Route
POST http://localhost:8080/entrance
Content-Type: application/json
Authorization: Token ACCESS_TOKEN_HERE

{
  "eventId": "soft",
  "date": "1999-06-02T00:00:00.000Z",
  "total": "rouge"
}

###------------------------------
###modif entrance
PUT http://localhost:8080/entrance/ID_HERE
Content-Type: application/json
Authorization: Token ACCESS_TOKEN_HERE

{
  "eventId": "softfd",
  "date": "1999-06-02T00:00:00.000Z",
  "total": "rougfe"
}


###------------------------------
###Del entrance
DELETE http://localhost:8080/ID_HERE
Content-Type: application/json
Authorization: Token ACCESS_TOKEN_HERE

###------------------------------
###get all entrance
get http://localhost:8080/entrance/
Content-Type: application/json
Authorization: Token ACCESS_TOKEN_HERE

###------------------------------
###get one entrance
get http://localhost:8080/entrance/ID_HERE
Content-Type: application/json
Authorization: Token ACCESS_TOKEN_HERE